# Generated by Django 2.1.5 on 2019-02-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190217_1021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
    ]
